version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/hall_management
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - ./backend:/app/backend # Map local backend directory to container
      - /app/backend/node_modules # Persist container node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network
    volumes:
      - ./frontend:/app/frontend # Map local frontend directory to container
      - /app/frontend/node_modules # Persist container node_modules

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hall_management
    ports:
      - "5432:5432"
    volumes:
      - ./db:/app/db # Helpful for sql exporting
      # - ./db:/docker-entrypoint-initdb.d/ # Automatically run this SQL file on initialization
      - ./db/hall_management.sql:/docker-entrypoint-initdb.d/init.sql # Automatically run this SQL file on initialization
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:
